# Generated by Django 6.0 on 2026-01-03 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_atuacao', models.TextField()),
                ('resumo_perfil', models.TextField()),
                ('origem_curriculo', models.CharField(max_length=255)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('nome_curriculo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('data_publicacao', models.DateField(auto_now_add=True)),
                ('link', models.TextField()),
                ('titulo', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('responsabilidades', models.TextField()),
                ('requisitos_obrigatorios', models.TextField()),
                ('diferencial', models.TextField()),
                ('requisitos_desejaveis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_competencia', models.CharField(max_length=100)),
                ('nivel_competencia', models.CharField(max_length=50)),
                ('descricao_competencia', models.TextField()),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.curriculo')),
            ],
        ),
        migrations.CreateModel(
            name='Educacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('nivel_educacao', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_conclusao', models.DateField()),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.curriculo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=17)),
                ('data_nascimento', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='curriculo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.usuario'),
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_candidatura', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('em_analise', 'Em análise'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='enviada', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recomendacoes', models.TextField()),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.curriculo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.usuario')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.vaga')),
            ],
        ),
    ]
