# Generated by Django 5.2.8 on 2025-11-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_curriculum_job_user_delete_polls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='area',
        ),
        migrations.AddField(
            model_name='job',
            name='requisitos',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='responsabilidade',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
